/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package midtermExamPackage;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Brandon
 */
public class midtermExamFrame extends javax.swing.JFrame {

    /**
     * Creates new form midtermExamFrame
     */
    public midtermExamFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        itemCodeTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        unitPriceTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        qtyTextField = new javax.swing.JTextField();
        addToCartButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        totalAmountTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        amountPaidTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        changeTextField = new javax.swing.JTextField();
        computeButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        itemComboBox = new javax.swing.JComboBox<>();
        itemNameComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("XYZ SARI-SARI STORE");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("<< POINT OF SALES SYSTEM >>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addGap(239, 239, 239))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("ITEM CODE: ");

        itemCodeTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        itemCodeTextField.setForeground(new java.awt.Color(0, 0, 0));
        itemCodeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemCodeTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemCodeTextFieldKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("DESCRIPTION");

        descriptionTextField.setEditable(false);
        descriptionTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        descriptionTextField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setText("UNIT PRICE");

        unitPriceTextField.setEditable(false);
        unitPriceTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unitPriceTextField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("QTY:");

        qtyTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        qtyTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyTextFieldKeyTyped(evt);
            }
        });

        addToCartButton.setBackground(new java.awt.Color(255, 255, 0));
        addToCartButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addToCartButton.setForeground(new java.awt.Color(0, 0, 0));
        addToCartButton.setText("ADD TO CART");
        addToCartButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addToCartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addToCartButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addToCartButtonMouseExited(evt);
            }
        });
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 153));
        jLabel7.setText("TOTAL AMOUNT");

        totalAmountTextField.setEditable(false);
        totalAmountTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        totalAmountTextField.setForeground(new java.awt.Color(0, 0, 0));
        totalAmountTextField.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 153));
        jLabel8.setText("AMOUNT PAID ");

        amountPaidTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        amountPaidTextField.setForeground(new java.awt.Color(0, 0, 0));
        amountPaidTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountPaidTextFieldKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 153));
        jLabel9.setText("CHANGE");

        changeTextField.setEditable(false);
        changeTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        computeButton.setBackground(new java.awt.Color(255, 255, 0));
        computeButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        computeButton.setForeground(new java.awt.Color(0, 0, 0));
        computeButton.setText("COMPUTE");
        computeButton.setToolTipText("");
        computeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        computeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                computeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                computeButtonMouseExited(evt);
            }
        });
        computeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(255, 255, 0));
        clearButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        clearButton.setForeground(new java.awt.Color(0, 0, 0));
        clearButton.setText("CLEAR");
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearButtonMouseExited(evt);
            }
        });
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 255, 0));
        exitButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("EXIT");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        itemComboBox.setBackground(new java.awt.Color(255, 255, 255));
        itemComboBox.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        itemComboBox.setForeground(new java.awt.Color(153, 255, 153));
        itemComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        itemNameComboBox.setBackground(new java.awt.Color(255, 255, 255));
        itemNameComboBox.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        itemNameComboBox.setForeground(new java.awt.Color(153, 255, 153));
        itemNameComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(itemCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(74, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(unitPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(qtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addToCartButton))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(totalAmountTextField)
                                                    .addComponent(amountPaidTextField)
                                                    .addComponent(changeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(itemNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(67, 67, 67))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(computeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(itemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(itemCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(unitPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(qtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addToCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(itemNameComboBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(amountPaidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(changeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(computeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartButtonMouseEntered
        addToCartButton.setBackground(Color.BLACK);
        addToCartButton.setForeground(Color.YELLOW);
    }//GEN-LAST:event_addToCartButtonMouseEntered

    private void addToCartButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartButtonMouseExited
        addToCartButton.setBackground(Color.YELLOW);
        addToCartButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_addToCartButtonMouseExited

    private void computeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_computeButtonMouseEntered
        computeButton.setBackground(Color.BLACK);
        computeButton.setForeground(Color.YELLOW);
    }//GEN-LAST:event_computeButtonMouseEntered

    private void computeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_computeButtonMouseExited
        computeButton.setBackground(Color.YELLOW);
        computeButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_computeButtonMouseExited

    private void clearButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseEntered
        clearButton.setBackground(Color.BLACK);
        clearButton.setForeground(Color.YELLOW);
    }//GEN-LAST:event_clearButtonMouseEntered

    private void clearButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseExited
        clearButton.setBackground(Color.YELLOW);
        clearButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_clearButtonMouseExited

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButton.setBackground(Color.BLACK);
        exitButton.setForeground(Color.YELLOW);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        exitButton.setBackground(Color.YELLOW);
        exitButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitButtonMouseExited

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
       try{
            String description = descriptionTextField.getText();
            String qty = qtyTextField.getText();
            int QTY = Integer.parseInt(qty);
            String unit = unitPriceTextField.getText();
            
            itemComboBox.addItem(unit);
           
            if(description.equals("Soy Sauce") && QTY == 1 || description.equals("Vinegar") && QTY == 1|| description.equals("Softdrinks") && QTY == 1 || 
                    description.equals("Sandwich Spread") && QTY == 1 || description.equals("Egg") && QTY == 1 || description.equals("Creamer") && QTY == 1 || description.equals("Coffee") && QTY == 1 || description.equals("Mineral Water") && QTY == 1 || description.equals("Junk Food") && QTY == 1){
                itemNameComboBox.addItem(description+"                             "+QTY+" piece");
            }else if(description.equals("Rice") && QTY == 1 || description.equals("LPG") && QTY == 1){
                itemNameComboBox.addItem(description+"                          "+QTY+" kilo");
            }else if(description.equals("Rice") && QTY >= 2 || description.equals("LPG") && QTY >= 2){
                itemNameComboBox.addItem(description+"                          "+QTY+" kilos");
            }else{
                itemNameComboBox.addItem(description+"                             "+QTY+" pieces");
            }
            
            
            int sum = 0;
            for (int i = 0; i < itemComboBox.getItemCount(); i++) {
                String numberStr = (String) itemComboBox.getItemAt(i);
                int number = Integer.parseInt(numberStr);
                sum += number;
            }
            String result = String.valueOf(sum);
            totalAmountTextField.setText(result);
            
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Error items","ERROR ADD TO CART ITEM",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_addToCartButtonActionPerformed

    private void computeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeButtonActionPerformed
        try{
            String amountPaid = amountPaidTextField.getText();
            int amount = Integer.parseInt(amountPaid);
            String totalAmount = totalAmountTextField.getText();
            int total = Integer.parseInt(totalAmount);
            
            int change = amount - total;
            String change_Total = String.valueOf(change);
            changeTextField.setText(change_Total);
           
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error no Total Amount and Amount Paid!","Error Details",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_computeButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
       itemCodeTextField.setText(null);
       descriptionTextField.setText(null);
       unitPriceTextField.setText(null);
       qtyTextField.setText(null);
       itemComboBox.removeAllItems();
       itemNameComboBox.removeAllItems();
       totalAmountTextField.setText(null);
       amountPaidTextField.setText(null);
       changeTextField.setText(null);
       itemCodeTextField.requestFocus();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
       System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void itemCodeTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemCodeTextFieldKeyTyped
        char c = evt.getKeyChar();
       
        if (!Character.isDigit(c)) {
            evt.consume();
        }  
    }//GEN-LAST:event_itemCodeTextFieldKeyTyped
    
    private final int soySauce = 11;
    private final int vinegar = 13;
    private final int rice = 50;
    private final int softdrinks = 15;
    private final int sandwichSpread = 30;
    private final int detergent = 20;
    private final int egg = 10;
    private final int lpg = 1000;
    private final int creamer = 5;
    private final int coffee = 12;
    private final int mineralWater = 25;
    private final int junkFood = 2;
    
   
    private void itemCodeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemCodeTextFieldKeyPressed
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                String text = itemCodeTextField.getText();
                int num = Integer.parseInt(text);
                switch (num) {
                    case 1 ->{
                            descriptionTextField.setText("Soy Sauce");
                            qtyTextField.setText("1");
                            String total = String.valueOf(soySauce);
                            unitPriceTextField.setText(total);
                        }
                    case 2 ->{
                            descriptionTextField.setText("Vinegar");
                            qtyTextField.setText("1");
                            String total = String.valueOf(vinegar);
                            unitPriceTextField.setText(total);
                        }
                    case 3 ->{
                            descriptionTextField.setText("Rice");
                            qtyTextField.setText("1");
                            String total = String.valueOf(rice);
                            unitPriceTextField.setText(total);
                        }
                    case 4 ->{
                            descriptionTextField.setText("Softdrinks");
                            qtyTextField.setText("1");
                            String total = String.valueOf(softdrinks);
                            unitPriceTextField.setText(total);
                    } 
                    case 5 ->{
                            descriptionTextField.setText("Sandwich Spread");
                            qtyTextField.setText("1");
                            String total = String.valueOf(sandwichSpread);
                            unitPriceTextField.setText( total);
                    }
                    case 6 ->{
                            descriptionTextField.setText("Detergent");
                            qtyTextField.setText("1");
                            String total = String.valueOf(detergent);
                            unitPriceTextField.setText(total);
                    }
                    case 7 ->{
                            descriptionTextField.setText("Egg");
                            qtyTextField.setText("1");
                            String total = String.valueOf(egg);
                            unitPriceTextField.setText(total);
                    }
                    case 8 ->{
                            descriptionTextField.setText("LPG");
                            qtyTextField.setText("1");
                            String total = String.valueOf(lpg);
                            unitPriceTextField.setText(total);
                    }
                    case 9 ->{
                            descriptionTextField.setText("Creamer");
                            qtyTextField.setText("1");
                            String total = String.valueOf(creamer);
                            unitPriceTextField.setText(total);
                    }
                    case 10 ->{
                            descriptionTextField.setText("Coffee");
                            qtyTextField.setText("1");
                            String total = String.valueOf(coffee);
                            unitPriceTextField.setText(total);
                    }
                    case 11 ->{
                            descriptionTextField.setText("Mineral Water");
                            qtyTextField.setText("1");
                            String total = String.valueOf(mineralWater);
                            unitPriceTextField.setText(total);
                    }
                    case 12 ->{
                            descriptionTextField.setText("Junk Food");
                            qtyTextField.setText("1");
                            String total = String.valueOf(junkFood);
                            unitPriceTextField.setText(total);
                    }
                    default ->{ 
                            JOptionPane.showMessageDialog(null, "Please Add Valid Item Code!","Error Item Code",JOptionPane.ERROR_MESSAGE);
                    }        
                }
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please Add Valid Item Code!","Error Item Code",JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_itemCodeTextFieldKeyPressed
    
     private void equation(int qty,int num){
         
        String text = itemCodeTextField.getText();
        num = Integer.parseInt(text);
        String qtys = qtyTextField.getText();
        qty = Integer.parseInt(qtys);
        
        if(num == 1){
            int result = qty * soySauce;
            String value = String.valueOf(result);
            unitPriceTextField.setText(value);
        }else if(num == 2){
            int result = qty * vinegar;
            String value = String.valueOf(result);
            unitPriceTextField.setText(value);
        }else if(num == 3){
            int result = qty * rice;
            String value = String.valueOf(result);
            unitPriceTextField.setText(value );
        }else if(num == 4){
            int result = qty * softdrinks;
            String value = String.valueOf(result);
            unitPriceTextField.setText(value);
        }else if(num == 5){
            int result = qty * sandwichSpread;
            String value = String.valueOf(result);
            unitPriceTextField.setText(value);
        }else if(num == 6){
            int result = qty * detergent;
            String value = String.valueOf(result);
            unitPriceTextField.setText(value);
        }else if(num == 7){
            int result = qty * egg;
            String value = String.valueOf(result);
            unitPriceTextField.setText(value);
        }else if(num == 8){
            int result = qty * lpg;
            String value = String.valueOf(result);
            unitPriceTextField.setText(value);
        }else if(num == 9){
            int result = qty * creamer;
            String value = String.valueOf(result);
            unitPriceTextField.setText(value);
        }else if(num == 10){
            int result = qty * coffee;
            String value = String.valueOf(result);
            unitPriceTextField.setText(value);
        }else if(num == 11){
            int result = qty * mineralWater;
            String value = String.valueOf(result);
            unitPriceTextField.setText(value);
        }else if(num == 12){
            int result = qty * junkFood;
            String value = String.valueOf(result);
            unitPriceTextField.setText(value);
        }
    }
    
    
    private void qtyTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTextFieldKeyPressed
       try{
           if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                String text = itemCodeTextField.getText();
                int num = Integer.parseInt(text);
                String qty = qtyTextField.getText();
                int QTY = Integer.parseInt(qty);
            
                equation(QTY,num);
            }
       }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Please Add Valid Quantity Number","Error Quantity",JOptionPane.ERROR_MESSAGE);
       }
       
    }//GEN-LAST:event_qtyTextFieldKeyPressed

    private void qtyTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTextFieldKeyTyped
        char c = evt.getKeyChar();
       
        if (!Character.isDigit(c)) {
            evt.consume();
        }  
    }//GEN-LAST:event_qtyTextFieldKeyTyped

    private void amountPaidTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountPaidTextFieldKeyTyped
        char c = evt.getKeyChar();
       
        if (!Character.isDigit(c)) {
            evt.consume();
        }  
    }//GEN-LAST:event_amountPaidTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(midtermExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(midtermExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(midtermExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(midtermExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new midtermExamFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartButton;
    private javax.swing.JTextField amountPaidTextField;
    private javax.swing.JTextField changeTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton computeButton;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField itemCodeTextField;
    private javax.swing.JComboBox<String> itemComboBox;
    private javax.swing.JComboBox<String> itemNameComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField qtyTextField;
    private javax.swing.JTextField totalAmountTextField;
    private javax.swing.JTextField unitPriceTextField;
    // End of variables declaration//GEN-END:variables
}
